- name: Lighthouse CI Action
  uses: treosh/lighthouse-ci-action@v9
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://cirriussolutions.com/
            https://cirriussolutions.com/why-choose-us-salesforce-partner/
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
