name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://veteranscarecenters.org/wp-admin
            https://veteranscarecenters.org/wp-login.php?redirect_to=https%3A%2F%2Fveteranscarecenters.org%2Fwp-admin%2F&reauth=1
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
